export const MODAL_TYPES = {
  BRAND: "BRAND",
  CATEGORY: "CATEGORY",
  UNIT_MASTER: "UNIT_MASTER",
  GST: "GST",
  HSN: "HSN",
  TAX_GROUP: "TAX_GROUP",
  USER: "USER",
  QUICK_ADD_PRODUCT: "QUICK_ADD_PRODUCT",
  VARIANT_ATTRIBUTE: "VARIANT_ATTRIBUTE",
};
